config/routes.rb
Rails.application.routes.draw do
  resources :receipts

  resources :cart_items

  resources :line_items

  resources :carts

  get 'carts/show'

  resources :items do
    collection { post :import}
  end

  resources :employees

  resources :companies do 
    collection { post :import }
  end

  devise_for :users, :controllers => { registrations: 'registrations' } 
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/books'
  get 'welcome/checkout'
  get 'welcome/thank_you'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'

  resources :invoices
  
  
  root to: 'welcome#index'
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, :dependent => :destroy
  
  def add_item(item_id)
    current_item = cart_items.where(:item_id => item_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = CartItem.new(:item_id => item_id)
      cart_items << current_item
    end
    current_item
  end
  
  def total_price
    cart_items.to_a.sum { |item| item.total_price }
  end 
  
  def total_item
    cart_items.to_a.sum { |item| item.quantity }
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart
  belongs_to :receipt
  
  def total_price
    item.price * quantity
  end
  
end

app/models/company.rb
class Company < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # exclamation point is added so that if something doesn't work an error will be thrown
      Company.create! row.to_hash
    end
  end
  
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |company|
        csv << company.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :salesperson
end

app/models/invoice_search.rb
class InvoiceSearch 
  attr_reader :date_from, :date_to
  
  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end
  
  def scope
    Invoice.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end
  
  private
  
  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  has_many :cart_items
  
  before_destroy :ensure_not_referenced_by_any_cart_item
  
  def ensure_not_referenced_by_any_cart_item
    if cart_items.count.zero?
      return true
    else
      errors[:base] << "Items are present in cart"
      return false
    end
  end
  
  # search bar for item database
  def self.search(search)
    where("title LIKE ? ", "%#{search}%")
  end
  
  def self.query(query)
    where("author LIKE ? ", "%#{query}%")
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Item.create! row.to_hash
    end
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  
  PAYMENT_TYPES = [ "Online banking", "Credit Card", "PayPal"]
  
  validates :name, :address, :email, presence: true
  
  validates :pay_type, inclusion: PAYMENT_TYPES
  
  def add_cart_items_from_cart(cart)
    cart.cart_items.each do |item|
      item.cart_id = nil
      cart_items << item
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  def add
    id = params[:id]
    
    cart = session[:cart] ||= {}
    cart[id] = (cart[id] || 0) + 1
        
    redirect_to :action => :index
  end

  def index
    @cart = session[:cart] || {}
  end
  
  def change
  cart = session[:cart]
  id = params[:id];
  quantity = params[:quantity].to_i
  if cart and cart[id]
    unless quantity <= 0
      cart[id] = quantity
    else
      cart.delete id
    end
  end
    redirect_to :action => :index
  end
  
  def checkout
    flash[:notice] = "CHECKOUT IS NOT IMPLEMENTED YET!!!"
    redirect_to :action => :index
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @carts = Cart.all
    respond_with(@carts)
  end

  def show
    respond_with(@carts)  
  end

  def new
    @cart = Cart.new
    respond_with(@cart)
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.save
    respond_with(@cart)
  end

  def update
    @cart.update(cart_params)
    respond_with(@cart)
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id] = nil
    
    respond_to do |format|
      format.html { redirect_to(items_path, :notice => 'Your cart is currently empty')}
      format.xml {head :ok}
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cart = current_cart
    if params[:search] 
      @items = Item.search(params[:search]).paginate(:per_page => 5, :page => params[:page])
      respond_with(@items)
    else
      @items = Item.paginate(:per_page => 5, :page => params[:page])
    end
  end

  def show
    respond_with(@item)
  end
  
  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    respond_with(@item)
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end
  
  def import
    Item.import(params[:file])
    redirect_to items_path, notice: "Upload successful"
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:author, :title, :description, :price, :image_url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<h2> Your Shopping Cart</h2>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Author</th>
          <th>Title</th>
          <th>Quantity</th>
          <th>Item Total</th>
      </thead>
      <tbody>
        <% for item in @cart.cart_items %>
        <tr>
          <td><%= item.item.author %></td>
          <td><%= item.item.title %></td>
          <td><%= item.quantity %></td>
          <td><%= number_to_currency(item.total_price, :unit => "£") %></td>
        </tr>
        <% end %>
        <tr class="total_line">
          <td colspan="2">Total</td>
          <td class="total_cell"><%= @cart.total_item %></td>
          <td class="total_cell"><%= number_to_currency(@cart.total_price, :unit => "£") %></td>
        </tr>
      </tbody>
   </table>
    <% if user_signed_in? %>
    <%= button_to 'Checkout', new_receipt_path, method: :get %>
    <%= button_to 'Empty Cart', @cart, :method => :delete, :confirm => 'Are you sure>' %>
    <% else %>
    <%= button_to 'Empty Cart', @cart, :method => :delete, :confirm => 'Are you sure>' %>
    <p>You will need to <%= link_to 'Sign up', new_user_registration_path, class: 'btn' %> or 
    <%= link_to 'Login', new_user_session_path, class: 'btn btn-success' %> to proceed to the checkout.</p>
    <% end %>