config/routes.rb
Rails.application.routes.draw do
  resources :receipts

  resources :cart_items

  resources :line_items

  resources :carts

  get 'carts/show'

  resources :items do
    collection { post :import}
  end

  resources :employees

  resources :companies do 
    collection { post :import }
  end

  devise_for :users, :controllers => { registrations: 'registrations' } 
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/books'
  get 'welcome/checkout'
  get 'welcome/thank_you'
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'

  resources :invoices
  
  
  root to: 'welcome#index'
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, :dependent => :destroy
  
  def add_item(item_id)
    current_item = cart_items.where(:item_id => item_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = CartItem.new(:item_id => item_id)
      cart_items << current_item
    end
    current_item
  end
  
  def total_price
    cart_items.to_a.sum { |item| item.total_price }
  end 
  
  def total_item
    cart_items.to_a.sum { |item| item.quantity }
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart
  belongs_to :receipt
  
  def total_price
    item.price * quantity
  end
  
end

app/models/company.rb
class Company < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # exclamation point is added so that if something doesn't work an error will be thrown
      Company.create! row.to_hash
    end
  end
  
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |company|
        csv << company.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :salesperson
end

app/models/invoice_search.rb
class InvoiceSearch 
  attr_reader :date_from, :date_to
  
  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end
  
  def scope
    Invoice.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end
  
  private
  
  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  has_many :cart_items
  
  before_destroy :ensure_not_referenced_by_any_cart_item
  
  def ensure_not_referenced_by_any_cart_item
    if cart_items.count.zero?
      return true
    else
      errors[:base] << "Items are present in cart"
      return false
    end
  end
  
  # search bar for item database
  def self.search(search)
    where("title LIKE ? ", "%#{search}%")
  end
  
  def self.query(query)
    where("author LIKE ? ", "%#{query}%")
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Item.create! row.to_hash
    end
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  
  PAYMENT_TYPES = [ "Online banking", "Credit Card", "PayPal"]
  
  validates :name, :address, :email, presence: true
  
  validates :pay_type, inclusion: PAYMENT_TYPES
  
  def add_cart_items_from_cart(cart)
    cart.cart_items.each do |item|
      item.cart_id = nil
      cart_items << item
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EZbookz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container"> 
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Books", items_path %></li>
    <li><%= link_to "About us", welcome_about_path %></li>
    <li><%= link_to "Contact", welcome_contact_path %></li>
    <li><%= link_to "Your Cart", @cart %></li>
    <li><a href="">Items:<%= @cart.total_item %>, Price: <%= number_to_currency(@cart.total_price, :unit => "£") %></a></li>
    <!--<li><%= link_to "Invoices", invoices_path %></li>-->
    <% if user_signed_in? %>
    <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%=link_to current_user.email, edit_user_registration_path%></li>
        <li><%= link_to "Purchases", receipts_path %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        </li>
      </ul>
    </li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <li><%= link_to "Login", new_user_session_path %></li>
    <% end %>
  </ul>
  
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  
<%= yield %>

</div>
</body>
</html>